In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/dirty_cafe_sales.csv')
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
df['Item'].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

In [ ]:
df['Item'] = df['Item'].replace(['UNKNOWN','ERROR'], np.nan)

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                 969
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
missing_rate = df['Item'].isnull().mean() * 100
print(missing_rate,'%')

9.69 %

In [ ]:
df = df.dropna(subset='Item')

In [ ]:
df['Quantity'].value_counts(dropna=False)

Quantity
5          1834
2          1778
4          1681
3          1661
1          1657
UNKNOWN     153
ERROR       146
NaN         121
Name: count, dtype: int64

In [ ]:
df['Quantity'] = df['Quantity'].replace(['UNKNOWN','ERROR'], np.nan)

In [ ]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [ ]:
df['Quantity'].isnull().sum()

np.int64(420)

In [ ]:
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce').astype('float')
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce').astype('float')

In [ ]:
menu = df.groupby('Item')['Price Per Unit'].median()
menu

Item
Cake        3.0
Coffee      2.0
Cookie      1.0
Juice       3.0
Salad       5.0
Sandwich    4.0
Smoothie    4.0
Tea         1.5
Name: Price Per Unit, dtype: float64

In [ ]:
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Item'].map(menu))

In [ ]:
df.loc[
    df['Quantity'].isna(),
    'Quantity'
] = df['Total Spent'] / df['Price Per Unit']

In [ ]:
df['Quantity'].isnull().sum()

np.int64(20)

In [ ]:
df[df['Quantity'].isna()]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
236,TXN_8562645,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-18
278,TXN_3229409,Juice,NaN,3.0,NaN,Cash,Takeaway,2023-04-15
641,TXN_2962976,Juice,NaN,3.0,NaN,NaN,NaN,2023-03-17
738,TXN_8696094,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-05-14
2796,TXN_9188692,Cake,NaN,3.0,NaN,Credit Card,NaN,2023-12-01
3203,TXN_4565754,Smoothie,NaN,4.0,NaN,Digital Wallet,Takeaway,2023-10-06
3224,TXN_6297232,Coffee,NaN,2.0,NaN,NaN,NaN,2023-04-07
3401,TXN_3251829,Tea,NaN,1.5,NaN,Digital Wallet,In-store,2023-07-25
4257,TXN_6470865,Coffee,NaN,2.0,NaN,Digital Wallet,Takeaway,2023-09-18
5841,TXN_5884081,Cookie,NaN,1.0,NaN,Digital Wallet,In-store,2023-07-05
7029,TXN_4628338,Coffee,NaN,2.0,NaN,Cash,NaN,2023-12-25
7297,TXN_9944500,Smoothie,NaN,4.0,NaN,Cash,In-store,2023-01-03
8021,TXN_2428781,Salad,NaN,5.0,NaN,NaN,In-store,2023-05-09
8443,TXN_2023651,Sandwich,NaN,4.0,NaN,Cash,In-store,2023-05-25
8465,TXN_9669616,Coffee,NaN,2.0,NaN,NaN,ERROR,2023-06-03
8479,TXN_1547245,Sandwich,NaN,4.0,NaN,NaN,Takeaway,2023-09-11
8574,TXN_2546684,Juice,NaN,3.0,NaN,Digital Wallet,Takeaway,2023-04-08
8732,TXN_4550558,Cookie,NaN,1.0,NaN,Credit Card,In-store,2023-08-04
9590,TXN_9924732,Sandwich,NaN,4.0,NaN,Credit Card,In-store,2023-01-18
9869,TXN_1975184,Coffee,NaN,2.0,NaN,Digital Wallet,NaN,2023-01-15

In [ ]:
missing_rate_quantity = df['Quantity'].isnull().mean() * 100
print(missing_rate_quantity,'%')

0.22145941756173182 %

In [ ]:
df = df.dropna(subset='Quantity')

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent          432
Payment Method      2323
Location            2940
Transaction Date     143
dtype: int64

In [ ]:
df['Price Per Unit'].value_counts(dropna=False)

Price Per Unit
3.0    2306
4.0    2221
2.0    1160
5.0    1146
1.0    1090
1.5    1088
Name: count, dtype: int64

In [ ]:
df['Total Spent'].value_counts(dropna=False)

Total Spent
6.0     882
12.0    851
4.0     836
3.0     832
20.0    676
15.0    659
8.0     616
10.0    475
2.0     450
NaN     432
9.0     429
5.0     415
16.0    397
25.0    238
7.5     220
1.0     210
4.5     203
1.5     190
Name: count, dtype: int64

In [ ]:
df.loc [
    df['Total Spent'].isna(),
    'Total Spent'
] = df['Price Per Unit'] * df['Quantity']

In [ ]:
df['Total Spent'].isnull().sum()

np.int64(0)

In [ ]:
df  = df.drop(columns=['Tptal Spent'])

In [ ]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5.0,4.0,20.0,Credit Card,NaN,2023-03-31
7,TXN_6699534,Sandwich,4.0,4.0,16.0,Cash,UNKNOWN,2023-10-28
9,TXN_2064365,Sandwich,5.0,4.0,20.0,NaN,In-store,2023-12-31
10,TXN_2548360,Salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07
11,TXN_3051279,Sandwich,2.0,4.0,8.0,Credit Card,Takeaway,ERROR

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2323
Location            2940
Transaction Date     143
dtype: int64

In [ ]:
df['Payment Method'] = df['Payment Method'].replace(['UNKNOWN','ERROR'], np.nan)

In [ ]:
df['Payment Method'].value_counts(dropna=False)

Payment Method
NaN               2870
Digital Wallet    2059
Cash              2042
Credit Card       2040
Name: count, dtype: int64

In [ ]:
missing_rate_payment = df['Payment Method'].isnull().mean() * 100
print(missing_rate_payment,'%')

31.84996115858395 %

In [ ]:
df['Location'].value_counts(dropna=False)

Location
NaN         2940
Takeaway    2719
In-store    2715
ERROR        325
UNKNOWN      312
Name: count, dtype: int64

In [ ]:
df['Location'] = df['Location'].replace(['UNKNOWN','ERROR'], np.nan)

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2870
Location            3577
Transaction Date     143
dtype: int64

In [ ]:
missing_rate_location = df['Location'].isnull().mean() * 100
print(missing_rate_location,'%')

39.69592720008878 %

In [ ]:
df['Transaction Date'].value_counts(dropna=False)

Transaction Date
UNKNOWN       145
NaN           143
ERROR         130
2023-03-13     39
2023-07-24     37
             ...
2023-02-17     13
2023-07-22     13
2023-01-24     13
2023-09-24     13
2023-04-22     12
Name: count, Length: 368, dtype: int64

In [ ]:
df['Transaction Date'] = df['Transaction Date'].replace(['UNKNOWN','ERROR'], np.nan)

In [ ]:
df.isnull().sum()

Transaction ID         0
Item                   0
Quantity               0
Price Per Unit         0
Total Spent            0
Payment Method      2870
Location            3577
Transaction Date     418
dtype: int64

In [ ]:
missing_rate_date = df['Transaction Date'].isnull().mean() * 100
print(missing_rate_date,'%')

4.638774830762402 %

In [ ]:
cleaned_cafe_sales = df
cleaned_cafe_sales.to_csv('cleaned_cafe_sales.csv', index=False)

In [ ]:
from google.colab import files
files.download('cleaned_cafe_sales.csv')

In [ ]:
cleaned_cafe_sales['Payment Method'] = cleaned_cafe_sales['Payment Method'].fillna('Unknown')
cleaned_cafe_sales['Location'] = cleaned_cafe_sales['Location'].fillna('Unknown')

In [ ]:
cleaned_cafe_sales.to_csv('cleaned_cafe_sales.csv', index=False)

In [ ]:
from google.colab import files
files.download('cleaned_cafe_sales.csv')